config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GOCDB/gocdb:
      branch: dev
      repo: https://github.com/GOCDB/gocdb.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GOCDB/gocdb git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-alizarin-affenpinscher.sh
        container: qc.acc_gamy-ecru-catfish
  QC.Doc:
    repos:
      github.com/GOCDB/gocdb find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-lemon-woodlouse.sh
        container: qc.doc_randy-amber-uguisu
      github.com/GOCDB/gocdb git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-sangria-yak.sh
        container: qc.doc_wheezy-asparagus-booby
      github.com/GOCDB/gocdb markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-heliotrope-kangaroo.sh
        container: qc.doc_goopy-cardinal-peccary
  QC.Lic:
    repos:
      github.com/GOCDB/gocdb licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cardinal-hamster.sh
        container: qc.lic_homely-plum-mongoose
  QC.Sty:
    repos:
      github.com/GOCDB/gocdb jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-gold-moorhen.sh
        container: qc.sty_wimpy-russet-sheepdog
  QC.Ver:
    repos:
      github.com/GOCDB/gocdb get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-ochre-zonkey.sh
        container: qc.ver_beady-dandelion-frog
timeout: 5400
